/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-background": "#e3e2e6",
        "inverse-on-surface": "#303034",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed-variant": "#653e00",
        "secondary-fixed-dim": "#4edea3",
        "primary": "#ffb3b1",
        "on-tertiary-fixed": "#2a1700",
        "primary-fixed": "#ffdad8",
        "on-primary-container": "#5b000e",
        "outline": "#ab8987",
        "on-secondary-fixed-variant": "#005236",
        "primary-container": "#ff535a",
        "on-primary-fixed-variant": "#92001c",
        "error-container": "#93000a",
        "on-primary-fixed": "#410007",
        "inverse-primary": "#bb162c",
        "outline-variant": "#5b403f",
        "on-secondary-container": "#00311f",
        "on-tertiary-container": "#3e2400",
        "surface-dim": "#121316",
        "tertiary-fixed": "#ffddb8",
        "on-error-container": "#ffdad6",
        "surface-variant": "#343538",
        "surface-bright": "#38393c",
        "error": "#ffb4ab",
        "secondary": "#4edea3",
        "on-error": "#690005",
        "primary-fixed-dim": "#ffb3b1",
        "secondary-container": "#00a572",
        "tertiary-container": "#ca8100",
        "on-secondary": "#003824",
        "surface-container-high": "#292a2d",
        "on-surface-variant": "#e4bebc",
        "on-surface": "#e3e2e6",
        "on-secondary-fixed": "#002113",
        "background": "#121316",
        "surface-tint": "#ffb3b1",
        "surface-container-lowest": "#0d0e11",
        "inverse-surface": "#e3e2e6",
        "on-tertiary": "#472a00",
        "on-primary": "#680011",
        "secondary-fixed": "#6ffbbe",
        "surface-container-low": "#1b1b1f",
        "surface-container-highest": "#343538",
        "surface": "#121316",
        "surface-container": "#1f1f23",
        "tertiary": "#ffb95f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "container-max": "1200px",
        "md": "24px",
        "sm": "12px",
        "base": "8px",
        "xl": "80px",
        "lg": "48px",
        "xs": "4px"
      },
      fontFamily: {
        "headline-md": ["Playfair Display"],
        "body-lg": ["Outfit"],
        "display-lg": ["Playfair Display"],
        "label-sm": ["Outfit"],
        "headline-sm": ["Playfair Display"],
        "display-lg-mobile": ["Playfair Display"],
        "body-md": ["Outfit"],
        "label-md": ["Outfit"]
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
